### ISSUE TITLE
Web 服务起不来啊

### ISSUE THREAD

**Issue by satouriko** [laobubu/ssland#5]
╭─root@VM-40-141-debian  /var/www/html  
╰─$ git clone https://github.com/laobubu/ssland.git ssland
Cloning into 'ssland'...
remote: Counting objects: 788, done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 788 (delta 38), reused 0 (delta 0), pack-reused 695
Receiving objects: 100% (788/788), 156.13 KiB | 136.00 KiB/s, done.
Resolving deltas: 100% (456/456), done.
Checking connectivity... done.
╭─root@VM-40-141-debian  /var/www/html  
╰─$ cd ssland 
╭─root@VM-40-141-debian  /var/www/html/ssland  ‹universal› 
╰─$ ls
config.py  django-manage.py  README.md         service    tools
core       quota             requirements.txt  ssland.py  web
╭─root@VM-40-141-debian  /var/www/html/ssland  ‹universal› 
╰─$ ./tools/setup.sh
Starting SSLand Setup...
[ALLOWED_HOSTS]
You must set the allowed hostname (domain or IP).
If you don't want to filter (not recommended), just press Enter key.
Hostname: linux.cool2645.com
You may edit web/settings.py file to add more
[SITE_CONFIG]
Site name [ default: SSLand ] = 
HTTP Port [ default: 8000 ] = 8091
[DJANGO]
Requirement already satisfied (use --upgrade to upgrade): Django==1.10.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): jsonfield in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): PyQRCode==1.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): shadowsocks in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): python-dateutil>=2.5.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Cleaning up...
Migrations for 'web':
  web/migrations/0001_initial.py:
    - Create model ProxyAccount
    - Create model Quota
    - Create model TrafficStat
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, web
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying sessions.0001_initial... OK
  Applying web.0001_initial... OK
Create one super user? [y/N] y
Username (leave blank to use 'root'): 
Email address: wangkule@cool2645.com
Password: 
Password (again): 
Superuser created successfully.
Notice: the super user will not have proxy account; you may create later.
[FINISHED]
To start SSLand daemon, please execute  ./ssland.py -d start
Start now? [y/N] y
ERROR:root:not running
started
╭─root@VM-40-141-debian  /var/www/html/ssland  ‹universal› 
╰─$ netstat -an | grep 8091
╭─root@VM-40-141-debian  /var/www/html/ssland  ‹universal› 
╰─$

**Comment by laobubu** [comment]
你手动看看 config.py 文件内容对不对，
或者把配置里面的 DEBUG 修改为 True 后，直接运行 sudo ./ssland.py 看看有没有报错。
那个配置脚本匆匆忙忙写的，还没有测试过…

**Comment by laobubu** [comment]
测试了程序，在 CentOS 6.7 （安装了 Python2.7）上可以使用。
检查一下是不是防火墙的问题吧

**Comment by satouriko** [comment]
╭─root@VM-40-141-debian  /var/www/html/ssland  ‹universal_› 
╰─$ ./ssland.py
[2016-09-23 16:15:59] DEBUG: using event model: epoll
Traceback (most recent call last):
  File "./ssland.py", line 78, in <module>
    init_all_service()
  File "./ssland.py", line 59, in init_all_service
    service.start(accounts[name], event_loop=main_loop)
  File "/mydata/www/html/ssland/service/Shadowsocks.py", line 101, in start
    _stat.add_to_loop()
  File "/mydata/www/html/ssland/core/ssutil.py", line 85, in add_to_loop
    self.ctx.connect()
  File "/mydata/www/html/ssland/core/ssutil.py", line 55, in connect
    socket.socket.connect(self, self.addr_remote)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(_args)
socket.error: [Errno 111] Connection refused

我是 Debian 8.0 Python 2.7.9

**Comment by satouriko** [comment]
没开防火墙

**Comment by laobubu** [comment]
可能是 Shadowsocks 服务器版本太老。Manager 功能是新版的 Shadowsocks 服务器（Python版本）的功能。

试试看更新一下：

```
pip install --upgrade shadowsocks
```

**Comment by laobubu** [comment]
啊对了，如果当时是使用 `apt` 方式安装的 Shadowsocks，那么基本上是用不了的。先卸载掉它，然后再运行 `setup.sh` ，安装脚本里会自动安装 Shadowsocks 的

**Comment by satouriko** [comment]
╭─root@VM-40-141-debian  ~  
╰─$ pip install --upgrade shadowsocks
Requirement already up-to-date: shadowsocks in /usr/local/lib/python2.7/dist-packages
Cleaning up...
╭─root@VM-40-141-debian  ~  
╰─$ cd /var/www/html/ssland 
╭─root@VM-40-141-debian  /var/www/html/ssland  ‹universal_› 
╰─$ ./ssland.py 
[2016-09-23 17:24:08] DEBUG: using event model: epoll
Traceback (most recent call last):
  File "./ssland.py", line 78, in <module>
    init_all_service()
  File "./ssland.py", line 59, in init_all_service
    service.start(accounts[name], event_loop=main_loop)
  File "/mydata/www/html/ssland/service/Shadowsocks.py", line 101, in start
    _stat.add_to_loop()
  File "/mydata/www/html/ssland/core/ssutil.py", line 85, in add_to_loop
    self.ctx.connect()
  File "/mydata/www/html/ssland/core/ssutil.py", line 55, in connect
    socket.socket.connect(self, self.addr_remote)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(_args)
socket.error: [Errno 111] Connection refused
╭─root@VM-40-141-debian  /var/www/html/ssland  ‹universal*› 
╰─$ 

不行呀　提示已经是最新了

**Comment by laobubu** [comment]
能否贴出 /var/log/shadowsocks.log 的内容（尤其最后十几行）。

可以试试看修改 config.py 里的 manager address 为 127.0.0.1:23145 之类的

**Comment by satouriko** [comment]
2016-09-23 14:11:08 INFO     entering manager mode
2016-09-23 14:11:08 INFO     adding server at linux.cool2645.com:54301
started
Traceback (most recent call last):
  File "/usr/local/bin/ssserver", line 9, in <module>
    load_entry_point('shadowsocks==2.8.2', 'console_scripts', 'ssserver')()
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/server.py", line 54, in main
    manager.run(config)
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/manager.py", line 192, in run
    Manager(config).run()
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/manager.py", line 78, in **init**
    self.add_port(a_config)
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/manager.py", line 89, in add_port
    self.stat_callback)
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/tcprelay.py", line 582, in **init**
    server_socket.bind(sa)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address
2016-09-23 14:13:06 INFO     entering manager mode
2016-09-23 14:13:06 INFO     adding server at linux.cool2645.com:54301
started
Traceback (most recent call last):
  File "/usr/local/bin/ssserver", line 9, in <module>
    load_entry_point('shadowsocks==2.8.2', 'console_scripts', 'ssserver')()
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/server.py", line 54, in main
    manager.run(config)
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/manager.py", line 192, in run
    Manager(config).run()
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/manager.py", line 78, in __init__
    self.add_port(a_config)
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/manager.py", line 89, in add_port
    self.stat_callback)
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/tcprelay.py", line 582, in **init**
    server_socket.bind(sa)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address
2016-09-23 16:16:00 INFO     entering manager mode
2016-09-23 16:16:00 INFO     adding server at linux.cool2645.com:54301
started
Traceback (most recent call last):
  File "/usr/local/bin/ssserver", line 9, in <module>
    load_entry_point('shadowsocks==2.8.2', 'console_scripts', 'ssserver')()
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/server.py", line 54, in main
    manager.run(config)
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/manager.py", line 192, in run
    Manager(config).run()
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/manager.py", line 78, in __init__
    self.add_port(a_config)
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/manager.py", line 89, in add_port
    self.stat_callback)
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/tcprelay.py", line 582, in **init**
    server_socket.bind(sa)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address
2016-09-23 17:24:08 INFO     entering manager mode
2016-09-23 17:24:08 INFO     adding server at linux.cool2645.com:54301
started
Traceback (most recent call last):
  File "/usr/local/bin/ssserver", line 9, in <module>
    load_entry_point('shadowsocks==2.8.2', 'console_scripts', 'ssserver')()
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/server.py", line 54, in main
    manager.run(config)
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/manager.py", line 192, in run
    Manager(config).run()
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/manager.py", line 78, in __init__
    self.add_port(a_config)
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/manager.py", line 89, in add_port
    self.stat_callback)
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/tcprelay.py", line 582, in **init**
    server_socket.bind(sa)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address

**Comment by satouriko** [comment]
```
那个原来是这样的啊

#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  Config Module.
#

DEBUG = True
# WIZARD_GENERATED = 'Fri Sep 23 14:12:40 CST 2016'

SITE_NAME = 'SSLand'
HTTP_PORT = 8091

SECRET_KEY = '2+amTc9+nITMAxHfOki00IVFr90LukUJ3qu7GVqLF8w='
DATABASE_FILENAME = 'db.sqlite3'

# Note: more setting about Django can be configured in `web/settings.py`

MODULES = {
    "Shadowsocks": {
        # see /service/Shadowsocks.py
        "executable": "ssserver",
        "config-file": "/etc/shadowsocks.json",
        "manager-address": "/var/run/shadowsocks-manager.sock",
    },

    # # Uncomment these to enable pptpd
    # "PPTP": {
    #     "executable": "service pptpd",
    #     "config-file": "/etc/ppp/chap-secrets"
    # }
}
```

**Comment by laobubu** [comment]
看样子不是 Shadowsocks 版本号的问题。

那么看一看是不是存在文件 /var/run/shadowsocks-manager.sock，如果有的话，把它删除，然后再试一次。

**Comment by satouriko** [comment]
是这样吗

╭─root@VM-40-141-debian  /var/www/html/ssland  ‹universal_› 
╰─$ rm /var/run/shadowsocks-manager.sock                                    1 ↵
╭─root@VM-40-141-debian  /var/www/html/ssland  ‹universal_› 
╰─$ ./ssland.py  
[2016-09-23 17:57:56] DEBUG: using event model: epoll
Traceback (most recent call last):
  File "./ssland.py", line 78, in <module>
    init_all_service()
  File "./ssland.py", line 59, in init_all_service
    service.start(accounts[name], event_loop=main_loop)
  File "/mydata/www/html/ssland/service/Shadowsocks.py", line 101, in start
    _stat.add_to_loop()
  File "/mydata/www/html/ssland/core/ssutil.py", line 85, in add_to_loop
    self.ctx.connect()
  File "/mydata/www/html/ssland/core/ssutil.py", line 55, in connect
    socket.socket.connect(self, self.addr_remote)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(_args)
socket.error: [Errno 111] Connection refused
╭─root@VM-40-141-debian  /var/www/html/ssland  ‹universal_› 
╰─$   

删了也启动不了呀

**Comment by laobubu** [comment]
呃 这就不知道了，试试看 ss-panel 吧……

2016年9月23日 下午5:58，"LI JIAHAO" notifications@github.com写道：
