### ISSUE TITLE
Cannot start with the ssland.py

### ISSUE THREAD

**Issue by c0mm4nd** [laobubu/ssland#8]
I have execute the setup steps, but at last I find that the server doesnt start.

So I tried directly to execute the ssland.py

The error msg as following:

```bash
root@vultr:/opt/ssland# ./ssland.py
[2017-10-06 22:04:54] DEBUG: using event model: epoll
Traceback (most recent call last):
  File "./ssland.py", line 78, in <module>
    init_all_service()
  File "./ssland.py", line 59, in init_all_service
    service.start(accounts[name], event_loop=main_loop)
  File "/opt/ssland/service/Shadowsocks.py", line 101, in start
    _stat.add_to_loop()
  File "/opt/ssland/core/ssutil.py", line 85, in add_to_loop
    self.ctx.connect()
  File "/opt/ssland/core/ssutil.py", line 55, in connect
    socket.socket.connect(self, self.addr_remote)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 2] No such file or directory
```

And the django has no bug while runserver.

System Info:

` Linux vultr.guest 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux `

Python Version

` Python 2.7.13`

and while writing this issue I also tried python3

```bash
Traceback (most recent call last):
  File "ssland.py", line 78, in <module>
    init_all_service()
  File "ssland.py", line 55, in init_all_service
    for name, service_config in config.MODULES.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

Help, please.
Thanks

**Comment by laobubu** [comment]
Please provide `sslocal --version`

**Comment by c0mm4nd** [comment]
I have changed my OS on VPS, and It works on Ubuntu. Thanks
